### ISSUE TITLE
Image may not show if page selected multiple times

### ISSUE THREAD

**Issue by Ruudt** [Ruudt/contao-page_images#5]
If a page gets more then one images assigned through more then one record then some images may not show.

**Comment by bschi** [comment]
Is there a fix already available?

**Comment by Ruudt** [comment]
No, only a workaround. Do not select pages more then once. I may not have the time to fix this before may. If anyone wants to help I'd be happy to accept the needed changes.

**Comment by bschi** [comment]
I programmed a quick fix that works for my purposes now. An extensive test I have not done.

**Comment by Ruudt** [comment]
I tried your code, but it only selects the first image of every entry that has the current page. (So if you have 3 images in one item and 100 in another then a common page between the two will only see the first images of ech of the two items)
